#{% set version = "1.0.1" %}
#{% set commit = "743fdbdb192dd0f07d51d6f94f8b47984484b54f" %}
{% set version = "1.0.0" %}
{% set commit = "db5d3131d16f57abd4f13d3f4b885d5f67bf6644" %}

package:
  name: pytorch
  version: {{ version }}

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: {{ commit }}
  patches:
    - 0001-Add-DCUDA_rt_LIBRARY-to-cmake-command.patch
    - 0002-lazy-bind-C-extension.patch
    - 0003-always-add-librt-to-requirements.patch
    - 0004-pass-module-linker-flags-to-cmake.patch
    # https://github.com/pytorch/pytorch/issues/4499
    # merged upstream in https://github.com/facebookincubator/gloo/pull/127
    - mkl_dnn_disable_Werror_and_mnative.patch
    - define_speed_unknown.patch
    - nccl_socket.patch

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}
    - cudnn {{ cudnn }}
    #- nccl
    # other requirements
    - python
    - numpy
    - setuptools
    - pyyaml
    - cffi
    - mkl-devel {{ mkl }}
    - typing
    - ninja
    - magma

  run:
    # GPU requirements
    - {{ pin_compatible('cudatoolkit') }}
    - {{ pin_compatible('cudnn') }}
    #- {{ pin_compatible('nccl') }}
    # other requirements
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - ninja

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
  imports:
    - torch
  source_files:
    - test
  commands:
    - python ./test/run_test.py -x cpp_extensions || true

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
